// <auto-generated />
// This file is auto-maintained alongside the EF Core migrations.
// It represents the current model state as of the last applied migration so that
// EF Core tooling can compute the incremental diff for the next migration.
//
// Provider  : PostgreSQL ≥ 14 (Npgsql.EntityFrameworkCore.PostgreSQL)
// Namespace : DataViewer.Infrastructure.Migrations.Postgresql
//
// DO NOT edit this file manually. Regenerate it by running:
//   dotnet ef migrations add <MigrationName> \
//     --project src/DataViewer.Infrastructure \
//     --startup-project src/DataViewer.API \
//     --namespace DataViewer.Infrastructure.Migrations.Postgresql

using System;
using DataViewer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataViewer.Infrastructure.Migrations.Postgresql
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── AuditLogEntries ───────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.AuditLogEntry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<int>("ActionType")
                    .HasColumnType("integer");

                b.Property<string>("IpAddress")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)");

                b.Property<string>("Parameters")
                    .HasColumnType("jsonb");

                b.Property<string>("ProfileName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<int?>("ResultCount")
                    .HasColumnType("integer");

                b.Property<string>("S3ObjectKey")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.Property<DateTime>("TimestampUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex(new[] { "ActionType", "TimestampUtc" }, "idx_audit_actiontype_timestamp")
                    .IsDescending(false, true);

                b.HasIndex(new[] { "TimestampUtc" }, "idx_audit_timestamp")
                    .IsDescending(true);

                b.HasIndex(new[] { "UserId", "TimestampUtc" }, "idx_audit_user_timestamp")
                    .IsDescending(false, true);

                b.ToTable("AuditLogEntries");
            });

            // ── CredentialProfiles ────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.CredentialProfile", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("AccessKeyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("BucketName")
                    .IsRequired()
                    .HasMaxLength(63)
                    .HasColumnType("character varying(63)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("CreatedByUserId")
                    .HasColumnType("uuid");

                // bytea: PostgreSQL binary type for the AES-encrypted Secret Access Key.
                b.Property<byte[]>("EncryptedSecretKey")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("KeyPrefix")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Region")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                // Unique partial index: only rows where IsDeleted = false.
                // PostgreSQL double-quoted identifier syntax in the filter expression.
                b.HasIndex(new[] { "Name" }, "idx_profile_name")
                    .IsUnique()
                    .HasFilter("\"IsDeleted\" = false");

                b.ToTable("CredentialProfiles");
            });

            // ── RefreshTokens ─────────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRevoked")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex(new[] { "TokenHash" }, "idx_refresh_token_hash")
                    .IsUnique();

                b.HasIndex(new[] { "UserId" }, "idx_refresh_user");

                b.ToTable("RefreshTokens");
            });

            // ── SystemSettings ────────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.SystemSettings", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer");

                b.Property<int>("BodySizeCapMb")
                    .HasColumnType("integer");

                b.Property<int>("JwtAccessTokenMinutes")
                    .HasColumnType("integer");

                b.Property<int>("JwtRefreshTokenHours")
                    .HasColumnType("integer");

                b.Property<int>("LockoutThreshold")
                    .HasColumnType("integer");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("SystemSettings");

                // Seed: singleton row with default values (SystemSettingsConfiguration.HasData).
                b.HasData(
                    new
                    {
                        Id = 1,
                        BodySizeCapMb = 10,
                        JwtAccessTokenMinutes = 15,
                        JwtRefreshTokenHours = 24,
                        LockoutThreshold = 5,
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                    });
            });

            // ── UserPreferences ───────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.UserPreference", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<int>("DefaultDateRangeDays")
                    .HasColumnType("integer");

                b.Property<int>("DefaultPageSize")
                    .HasColumnType("integer");

                b.Property<Guid?>("PreferredProfileId")
                    .HasColumnType("uuid");

                b.HasKey("UserId");

                b.ToTable("UserPreferences");
            });

            // ── Users ─────────────────────────────────────────────────────────
            modelBuilder.Entity("DataViewer.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("FailedLoginCount")
                    .HasColumnType("integer");

                b.Property<bool>("IsLocked")
                    .HasColumnType("boolean");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("LockoutUntil")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Role")
                    .HasColumnType("integer");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex(new[] { "Email" }, "idx_user_email");

                b.HasIndex(new[] { "UserName" }, "idx_user_username")
                    .IsUnique();

                b.ToTable("Users");
            });

            // ── Relationships ─────────────────────────────────────────────────

            modelBuilder.Entity("DataViewer.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("DataViewer.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("DataViewer.Domain.Entities.UserPreference", b =>
            {
                b.HasOne("DataViewer.Domain.Entities.User", "User")
                    .WithOne("Preference")
                    .HasForeignKey("DataViewer.Domain.Entities.UserPreference", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("DataViewer.Domain.Entities.User", b =>
            {
                b.Navigation("Preference");

                b.Navigation("RefreshTokens");
            });
#pragma warning restore 612, 618
        }
    }
}
