/**
 * dataViewerApi.ts
 * ================
 * RTK Query API service for the DataViewer application.
 *
 * Covers every endpoint described in the System Design API (§5):
 *   - Auth            (§5.2)
 *   - Credential Profiles (§5.3)
 *   - Transactions    (§5.4)
 *   - User Preferences (§5.5)
 *   - Admin Settings  (§5.6)
 *   - Audit Logs      (§5.7)
 *
 * Cache tags:
 *   CredentialProfile | UserPreferences | AdminSettings | AuditLog
 *
 * All hooks are auto-generated by RTK Query and re-exported at the bottom
 * of this file so consumers only need a single import.
 *
 * The custom baseQuery wraps Axios so that the 401 → refresh → retry logic
 * implemented in apiClient.ts is honoured automatically.
 */

import {
  BaseQueryFn,
  createApi,
  FetchBaseQueryError,
} from '@reduxjs/toolkit/query/react';
import type { AxiosError, AxiosRequestConfig } from 'axios';
import { apiClient } from '../../services/apiClient';
import type {
  ActivateProfileResult,
  AuditLogEntryDto,
  BodyContentType,
  CreateCredentialProfileRequest,
  CredentialProfileDto,
  GetAuditLogsParams,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  PagedResult,
  RefreshTokenRequest,
  SearchTransactionsParams,
  SystemSettingsDto,
  TestConnectionResult,
  TransactionDetailDto,
  TransactionSummaryDto,
  UpdateAdminSettingsRequest,
  UpdateCredentialProfileRequest,
  UpdateUserPreferencesRequest,
  UserPreferenceDto,
} from '../../types/api.types';

// Re-export for convenience so consumers only import from this file.
export type {
  ActivateProfileResult,
  AuditLogEntryDto,
  BodyContentType,
  CreateCredentialProfileRequest,
  CredentialProfileDto,
  GetAuditLogsParams,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  PagedResult,
  RefreshTokenRequest,
  SearchTransactionsParams,
  SystemSettingsDto,
  TestConnectionResult,
  TransactionDetailDto,
  TransactionSummaryDto,
  UpdateAdminSettingsRequest,
  UpdateCredentialProfileRequest,
  UpdateUserPreferencesRequest,
  UserPreferenceDto,
};

// ---------------------------------------------------------------------------
// Axios-based baseQuery
// ---------------------------------------------------------------------------
// RTK Query ships with `fetchBaseQuery` which uses the Fetch API. We use a
// custom baseQuery backed by our Axios instance so the 401 interceptor
// (transparent refresh + retry) defined in apiClient.ts is active for every
// RTK Query request.

interface AxiosBaseQueryArgs {
  url: string;
  method?: AxiosRequestConfig['method'];
  data?: unknown;
  params?: unknown;
  headers?: Record<string, string>;
}

/**
 * A baseQuery that delegates to the shared Axios instance.
 * Errors are normalised to RTK Query's FetchBaseQueryError shape.
 */
const axiosBaseQuery: BaseQueryFn<
  AxiosBaseQueryArgs,
  unknown,
  FetchBaseQueryError
> = async ({ url, method = 'GET', data, params, headers }) => {
  try {
    const response = await apiClient.request({
      url,
      method,
      data,
      params,
      headers,
    });

    // The apiClient uses validateStatus: () => true so we must check manually.
    if (response.status >= 400) {
      return {
        error: {
          status: response.status,
          // Preserve the backend ProblemDetails body for error handling.
          data: response.data,
        } as FetchBaseQueryError,
      };
    }

    return { data: response.data };
  } catch (axiosError) {
    const err = axiosError as AxiosError;
    return {
      error: {
        status: err.response?.status ?? 'FETCH_ERROR',
        data: err.response?.data ?? err.message,
      } as FetchBaseQueryError,
    };
  }
};

// ---------------------------------------------------------------------------
// Cache tag types
// ---------------------------------------------------------------------------

/**
 * Tag types used for cache invalidation across mutations.
 *
 *  CredentialProfile  — list and individual profile queries
 *  UserPreferences    — current-user preferences query
 *  AdminSettings      — system settings singleton query
 *  AuditLog           — audit log list query
 */
type TagType = 'CredentialProfile' | 'UserPreferences' | 'AdminSettings' | 'AuditLog';

// ---------------------------------------------------------------------------
// API definition
// ---------------------------------------------------------------------------

export const dataViewerApi = createApi({
  reducerPath: 'dataViewerApi',
  baseQuery: axiosBaseQuery,
  tagTypes: ['CredentialProfile', 'UserPreferences', 'AdminSettings', 'AuditLog'] as TagType[],

  endpoints: (builder) => ({
    // -----------------------------------------------------------------------
    // Auth (§5.2)
    // -----------------------------------------------------------------------

    /**
     * POST /auth/login
     * Returns accessToken + refreshToken. No cache tags — auth state is
     * managed by authSlice, not RTK Query cache.
     */
    login: builder.mutation<LoginResponse, LoginRequest>({
      query: (credentials) => ({
        url: '/auth/login',
        method: 'POST',
        data: credentials,
      }),
    }),

    /**
     * POST /auth/logout
     * Invalidates the provided refresh token server-side.
     * Returns void (204 No Content).
     */
    logout: builder.mutation<void, LogoutRequest>({
      query: (body) => ({
        url: '/auth/logout',
        method: 'POST',
        data: body,
      }),
    }),

    /**
     * POST /auth/refresh
     * Exchanges a refresh token for a new access token + refresh token.
     */
    refreshToken: builder.mutation<LoginResponse, RefreshTokenRequest>({
      query: (body) => ({
        url: '/auth/refresh',
        method: 'POST',
        data: body,
      }),
    }),

    // -----------------------------------------------------------------------
    // Credential Profiles (§5.3)
    // -----------------------------------------------------------------------

    /**
     * GET /credential-profiles
     * Paginated list — Admin only.
     */
    getCredentialProfiles: builder.query<
      PagedResult<CredentialProfileDto>,
      void
    >({
      query: () => ({ url: '/credential-profiles' }),
      providesTags: (result) =>
        result
          ? [
              // Individual tags for each profile enable targeted invalidation.
              ...result.data.map(({ id }) => ({
                type: 'CredentialProfile' as const,
                id,
              })),
              // List-level tag so new profile creation also triggers a refetch.
              { type: 'CredentialProfile' as const, id: 'LIST' },
            ]
          : [{ type: 'CredentialProfile' as const, id: 'LIST' }],
    }),

    /**
     * GET /credential-profiles/:id
     * Single profile by ID — Admin only.
     */
    getCredentialProfileById: builder.query<CredentialProfileDto, string>({
      query: (id) => ({ url: `/credential-profiles/${id}` }),
      providesTags: (_result, _error, id) => [
        { type: 'CredentialProfile' as const, id },
      ],
    }),

    /**
     * POST /credential-profiles
     * Create a new profile. Returns the created DTO (without secretAccessKey).
     */
    createCredentialProfile: builder.mutation<
      CredentialProfileDto,
      CreateCredentialProfileRequest
    >({
      query: (body) => ({
        url: '/credential-profiles',
        method: 'POST',
        data: body,
      }),
      // Invalidate the list so it refetches with the new profile.
      invalidatesTags: [{ type: 'CredentialProfile' as const, id: 'LIST' }],
    }),

    /**
     * PUT /credential-profiles/:id
     * Partial update. All fields are optional (send only what changes).
     */
    updateCredentialProfile: builder.mutation<
      CredentialProfileDto,
      { id: string; body: UpdateCredentialProfileRequest }
    >({
      query: ({ id, body }) => ({
        url: `/credential-profiles/${id}`,
        method: 'PUT',
        data: body,
      }),
      invalidatesTags: (_result, _error, { id }) => [
        { type: 'CredentialProfile' as const, id },
        { type: 'CredentialProfile' as const, id: 'LIST' },
      ],
    }),

    /**
     * DELETE /credential-profiles/:id
     * Soft-delete (sets isDeleted=true). Returns 204 No Content.
     */
    deleteCredentialProfile: builder.mutation<void, string>({
      query: (id) => ({
        url: `/credential-profiles/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: (_result, _error, id) => [
        { type: 'CredentialProfile' as const, id },
        { type: 'CredentialProfile' as const, id: 'LIST' },
      ],
    }),

    /**
     * POST /credential-profiles/:id/test
     * Test the S3 connection for a specific profile (ListObjectsV2 with MaxKeys=1).
     */
    testCredentialProfile: builder.mutation<TestConnectionResult, string>({
      query: (id) => ({
        url: `/credential-profiles/${id}/test`,
        method: 'POST',
      }),
      // No cache invalidation — this is a read-only probe.
    }),

    /**
     * POST /credential-profiles/:id/activate
     * Marks the given profile as active and all others inactive.
     */
    activateCredentialProfile: builder.mutation<ActivateProfileResult, string>({
      query: (id) => ({
        url: `/credential-profiles/${id}/activate`,
        method: 'POST',
      }),
      // Invalidate the whole list since isActive flags change across rows.
      invalidatesTags: [{ type: 'CredentialProfile' as const, id: 'LIST' }],
    }),

    // -----------------------------------------------------------------------
    // Transactions (§5.4)
    // -----------------------------------------------------------------------

    /**
     * GET /transactions
     * Search S3 transaction records with optional filter parameters.
     * Result is paginated. Audit entry written by the backend before response.
     */
    searchTransactions: builder.query<
      PagedResult<TransactionSummaryDto>,
      SearchTransactionsParams
    >({
      query: (params) => ({
        url: '/transactions',
        params,
      }),
      // Transactions are read-only from S3 — no cache tags needed.
    }),

    /**
     * GET /transactions/:s3KeyBase64
     * Full transaction detail including request/response headers and body.
     * The s3Key must be URL-safe Base64 encoded by the caller.
     * Audit entry written by the backend before response.
     */
    getTransactionDetail: builder.query<TransactionDetailDto, string>({
      query: (s3KeyBase64) => ({
        url: `/transactions/${encodeURIComponent(s3KeyBase64)}`,
      }),
      // Individual records from S3 — no cache tags needed.
    }),

    // -----------------------------------------------------------------------
    // User Preferences (§5.5)
    // -----------------------------------------------------------------------

    /**
     * GET /users/me/preferences
     * Returns the authenticated user's stored preferences.
     */
    getUserPreferences: builder.query<UserPreferenceDto, void>({
      query: () => ({ url: '/users/me/preferences' }),
      providesTags: [{ type: 'UserPreferences' as const, id: 'ME' }],
    }),

    /**
     * PUT /users/me/preferences
     * Partial update — send only the fields you want to change.
     */
    updateUserPreferences: builder.mutation<
      UserPreferenceDto,
      UpdateUserPreferencesRequest
    >({
      query: (body) => ({
        url: '/users/me/preferences',
        method: 'PUT',
        data: body,
      }),
      invalidatesTags: [{ type: 'UserPreferences' as const, id: 'ME' }],
    }),

    // -----------------------------------------------------------------------
    // Admin Settings (§5.6)
    // -----------------------------------------------------------------------

    /**
     * GET /admin/settings
     * Returns the singleton system settings row — Admin only.
     */
    getAdminSettings: builder.query<SystemSettingsDto, void>({
      query: () => ({ url: '/admin/settings' }),
      providesTags: [{ type: 'AdminSettings' as const, id: 'SINGLETON' }],
    }),

    /**
     * PUT /admin/settings
     * Partial update of system settings — Admin only.
     */
    updateAdminSettings: builder.mutation<
      SystemSettingsDto,
      UpdateAdminSettingsRequest
    >({
      query: (body) => ({
        url: '/admin/settings',
        method: 'PUT',
        data: body,
      }),
      invalidatesTags: [{ type: 'AdminSettings' as const, id: 'SINGLETON' }],
    }),

    // -----------------------------------------------------------------------
    // Audit Logs (§5.7)
    // -----------------------------------------------------------------------

    /**
     * GET /audit-logs
     * Paginated, filterable audit log — Admin only.
     * All filter parameters are optional.
     */
    getAuditLogs: builder.query<
      PagedResult<AuditLogEntryDto>,
      GetAuditLogsParams
    >({
      query: (params) => ({
        url: '/audit-logs',
        params,
      }),
      providesTags: (result) =>
        result
          ? [
              ...result.data.map(({ id }) => ({
                type: 'AuditLog' as const,
                id,
              })),
              { type: 'AuditLog' as const, id: 'LIST' },
            ]
          : [{ type: 'AuditLog' as const, id: 'LIST' }],
    }),
  }),
});

// ---------------------------------------------------------------------------
// Auto-generated hooks — exported for use across the application
// ---------------------------------------------------------------------------
// ASSUMPTION: RTK Query generates hook names by prefixing query endpoints with
// "use" and appending "Query", and mutation endpoints with "use" and "Mutation".

export const {
  // Auth
  useLoginMutation,
  useLogoutMutation,
  useRefreshTokenMutation,

  // Credential Profiles
  useGetCredentialProfilesQuery,
  useGetCredentialProfileByIdQuery,
  useCreateCredentialProfileMutation,
  useUpdateCredentialProfileMutation,
  useDeleteCredentialProfileMutation,
  useTestCredentialProfileMutation,
  useActivateCredentialProfileMutation,

  // Transactions
  useSearchTransactionsQuery,
  useGetTransactionDetailQuery,

  // User Preferences
  useGetUserPreferencesQuery,
  useUpdateUserPreferencesMutation,

  // Admin Settings
  useGetAdminSettingsQuery,
  useUpdateAdminSettingsMutation,

  // Audit Logs
  useGetAuditLogsQuery,
} = dataViewerApi;
